### ISSUE TITLE
DRAMSpec build error

### ISSUE THREAD

**Issue by asifuet** [tukl-msd/DRAMSpec#12]
Hi,

I want to build the DRAMSpec tool. I have installed the boost v1.63 and have set the path in .pro. When I run the test script, it gives erros (mostly on undefined units). Some lines from the console erros are as follows. Any help on this would be appreciated.

core/Bank.cpp:61:18: note: in expansion of macro ‘SCALE_QUANTITY’
   bankStorage =  SCALE_QUANTITY(channelSize, drs::bit_unit) / nBanks;
                  ^
core/Bank.cpp:61:69: error: expected ‘)’ before ‘;’ token
   bankStorage =  SCALE_QUANTITY(channelSize, drs::bit_unit) / nBanks;
                                                                     ^
In file included from core/../parser/../expandedBoostUnits/Units/capacitance_per_length.h:44:0,
                 from core/../parser/../expandedBoostUnits/Units/dramSpec_units.h:47,
                 from core/../parser/TechnologyValues.h:57,
                 from core/SubArray.h:47,
                 from core/Tile.h:47,
                 from core/Bank.h:46,
                 from core/Bank.cpp:41:
core/Bank.cpp: In member function ‘void Bank::bankLogicAssess()’:
core/Bank.cpp:95:55: error: ‘bit_unit’ is not a member of ‘drs’
   effectivePageStorage = (SCALE_QUANTITY(pageStorage, drs::bit_unit)
                                                       ^
core/../parser/../expandedBoostUnits/Units/../dramSpecUnitsSystem.h:67:32: note: in definition of macro ‘SCALE_QUANTITY’
     (static_cast<bu::quantity< to >> (from))
                                ^
core/Bank.cpp:95:55: error: ‘bit_unit’ is not a member of ‘drs’
   effectivePageStorage = (SCALE_QUANTITY(pageStorage, drs::bit_unit)
                                                       ^
core/../parser/../expandedBoostUnits/Units/../dramSpecUnitsSystem.h:67:32: note: in definition of macro ‘SCALE_QUANTITY’
     (static_cast<bu::quantity< to >> (from))
                                ^
core/Bank.cpp:95:42: error: ‘TechnologyValues::pageStorage’ cannot appear in a constant-expression
   effectivePageStorage = (SCALE_QUANTITY(pageStorage, drs::bit_unit)
                                          ^
core/../parser/../expandedBoostUnits/Units/../dramSpecUnitsSystem.h:67:39: note: in definition of macro ‘SCALE_QUANTITY’
     (static_cast<bu::quantity< to >> (from))
                                       ^
core/../parser/../expandedBoostUnits/Units/../dramSpecUnitsSystem.h:67:43: error: template argument 1 is invalid
     (static_cast<bu::quantity< to >> (from))
                                           ^
core/Bank.cpp:95:27: note: in expansion of macro ‘SCALE_QUANTITY’
   effectivePageStorage = (SCALE_QUANTITY(pageStorage, drs::bit_unit)
                           ^
core/../parser/../expandedBoostUnits/Units/../dramSpecUnitsSystem.h:67:44: error: expected ‘>’ before ‘)’ token
     (static_cast<bu::quantity< to >> (from))
                                            ^
core/Bank.cpp:95:27: note: in expansion of macro ‘SCALE_QUANTITY’
   effectivePageStorage = (SCALE_QUANTITY(pageStorage, drs::bit_unit)
                           ^
core/../parser/../expandedBoostUnits/Units/../dramSpecUnitsSystem.h:67:44: error: expected ‘(’ before ‘)’ token
     (static_cast<bu::quantity< to >> (from))
                                            ^
core/Bank.cpp:95:27: note: in expansion of macro ‘SCALE_QUANTITY’
   effectivePageStorage = (SCALE_QUANTITY(pageStorage, drs::bit_unit)
                           ^
core/../parser/../expandedBoostUnits/Units/../dramSpecUnitsSystem.h:67:44: error: expected primary-expression before ‘)’ token
     (static_cast<bu::quantity< to >> (from))
                                            ^
core/Bank.cpp:95:27: note: in expansion of macro ‘SCALE_QUANTITY’
   effectivePageStorage = (SCALE_QUANTITY(pageStorage, drs::bit_unit)
                           ^
core/Bank.cpp:98:28: error: expected ‘)’ before ‘;’ token
                           );
                            ^
Makefile:353: recipe for target 'build/debug/.obj/Bank.o' failed
make: *** [build/debug/.obj/Bank.o] Error 1
Testing...
./runTests.sh: line 12: ./build/debug/dramspec_test: No such file or directory

**Comment by myzinsky** [comment]
What is the output of 
```bash
c++ --version
```

**Comment by asifuet** [comment]
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.

**Comment by AndreChinazzo** [comment]
Can you please copy the output of
`qmake --version`

**Comment by asifuet** [comment]
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu

**Comment by AndreChinazzo** [comment]
Is it possible for you to update your Qt? The outuput for me is
QMake version 3.0
Using Qt version 5.2.1 in ...

I cannot tell for sure if that is the problem, but it can very well be.

**Comment by asifuet** [comment]
Ok, I can try that.

**Comment by AndreChinazzo** [comment]
Whenever you manage to do it, please let me know if it worked or not. If it does, I will include this version dependency to the readme. 
If it doesn't work, try re-cloning the repository from scratch.

**Comment by asifuet** [comment]
Hi,
I updated the Qt to 5.5.1 and it works fine now. Here is the output of my qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu
Thanks.

**Comment by AndreChinazzo** [comment]
Good!
If you find any other problem, please let us know.
